### ISSUE TITLE
Check and update the dependencies

### ISSUE THREAD

**Issue by shotozuro** [shotozuro/todoapp-nextjs#4]
Based on dependabot alerts, there are some dependencies with high severity. We need to update it to improve the security.

**Comment by saladinreborn** [comment]
It seems easy to do. Assign me to this issue. Here are what I plan to do:

1. Checking all the project dependencies.
2. If there's security issue for certain dependency, find the patched/fixed version and then update using patched/fixed version.

**Comment by shotozuro** [comment]
OK. Just go on and submit your PR.

**Comment by saladinreborn** [comment]
please check #5
